pre-push:
  parallel: true
  commands:
    check_inibase:
      run: npx -q tsx ./tests/inibase.test.ts
    check_inibase_advanced:
      run: npx -q tsx ./tests/inibase.advanced.test.ts
    check_transaction:
      run: npx -q tsx ./tests/transaction.test.ts
    check_durability:
      run: npx -q tsx ./tests/durability.test.ts
    check_expression:
      run: npx -q tsx ./tests/expression.test.ts
    check_utils:
      run: npx -q tsx ./tests/utils.test.ts